version: 2
jobs:
  test-python3:
    docker:
      # TODO(pascal): Revert to python:3 when
      # https://github.com/yaml/pyyaml/issues/193 is fixed.
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Install requirements for test
          command: pip install .[dev] mypy
      - run:
          name: Actually run the tests
          command: nosetests --with-coverage
      - run:
          name: Uploading coverage to codecov.io
          command: codecov
      - run:
          name: Check style errors
          command: pylint --load-plugins pylint_quotes emploi_store tests
      - run:
          name: Check type stubs
          command: stubtest emploi_store
  test-python2:
    docker:
      - image: python:2
    steps:
      - checkout
      - run:
          name: Install requirements for test
          command: pip install .[dev]
      - run:
          name: Actually run the tests
          command: nosetests --with-coverage
      - run:
          name: Uploading coverage to codecov.io
          command: codecov
      - run:
          name: Check style errors
          command: pylint --load-plugins pylint_quotes emploi_store tests
  deploy:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: Check that the tag version matches the lib version
          command: test "$CIRCLE_TAG" == "$(python -c "import setup; print(setup.__version__)")"
      - run:
          name: Build artifacts
          command: python setup.py sdist bdist_wheel
      - run:
          name: Prepare PyPi credentials
          command: |
            echo "[pypi]" > ~/.pypirc
            echo "  username = __token__" >> ~/.pypirc
            echo "  password = $PYPI_TOKEN" >> ~/.pypirc
      - run:
          name: Deploy to PyPi
          command: twine upload dist/*

workflows:
  version: 2
  build:
    jobs:
      - "test-python2":
          filters:
            tags:
              only: /.*/
      - "test-python3":
          filters:
            tags:
              only: /.*/
      - deploy:
          filters:
            tags:
              only: /\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
          requires:
            - test-python3
            - test-python2
          context:
            - PyPi
