version: 2
jobs:
  test-python3:
    docker:
      # TODO(pascal): Revert to python:3 when
      # https://github.com/yaml/pyyaml/issues/193 is fixed.
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Install requirements for test
          command: pip install .[dev]
      - run:
          name: Actually run the tests
          command: nosetests --with-coverage
      - run:
          name: Uploading coverage to codecov.io
          command: codecov
      - run:
          name: Check style errors
          command: pylint --load-plugins pylint_quotes emploi_store tests
  test-python2:
    docker:
      - image: python:2
    steps:
      - checkout
      - run:
          name: Install requirements for test
          command: pip install .[dev]
      - run:
          name: Actually run the tests
          command: nosetests --with-coverage
      - run:
          name: Uploading coverage to codecov.io
          command: codecov
      - run:
          name: Check style errors
          command: pylint --load-plugins pylint_quotes emploi_store tests

workflows:
  version: 2
  build:
    jobs:
      - "test-python2"
      - "test-python3"
